{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"b52f6014-fc7c-48ca-8c15-4b42d2c57654","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:35:11"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"27c54606-42e7-4e04-916b-2e3514443379","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:37:53"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"faa6caff-1d35-4177-8594-0374362eab53","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:43:48"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"a1204d85-bbb5-484f-a158-a11220fa6258","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:43:51"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"2cc8e039-d646-4531-95d0-094006a3671e","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:43:53"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"1e7702e8-dafb-4b7f-b821-b9303496eb86","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:44:14"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"d5cc4033-c1d3-49f4-854f-f961180ef0c4","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:44:16"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"cc118ead-1aad-4999-92ff-c2fbd87aaf81","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:44:18"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"a22f3f66-2350-4a0e-abd8-71ef5d48bc3d","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:48:43"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"668479c1-94af-4c29-99bb-a9ffc6858330","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:49:03"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script 20segundos.py","requestId":"36665dd0-ac7d-483b-92f2-355190cbe068","scriptId":"20segundos0","stackTrace":"Error: NameError: name 'joao' is not defined\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 22, in <module>\r\n      main()\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\20segundos.py\", line 9, in main\r\n      print(joao)\r\n            ^^^^","timestamp":"2024-01-06 11:52:48"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script smtester.py","requestId":"f098a57f-6505-4f81-a1f8-c94a723e6387","scriptId":"smtester0","stackTrace":"Error: NameError: name 'loads' is not defined. Did you mean: 'locals'?\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\smtester.py\", line 379, in <module>\r\n      loop.run_until_complete(main())\r\n    File \"C:\\Users\\joaop\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 653, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\smtester.py\", line 325, in main\r\n      data = loads(body)\r\n             ^^^^^","timestamp":"2024-01-07 13:44:55"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script smtester.py","requestId":"f098a57f-6505-4f81-a1f8-c94a723e6387","scriptId":"smtester1","stackTrace":"Error: NameError: name 'loads' is not defined. Did you mean: 'locals'?\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:511:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\smtester.py\", line 379, in <module>\r\n      loop.run_until_complete(main())\r\n    File \"C:\\Users\\joaop\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 653, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\smtester.py\", line 325, in main\r\n      data = loads(body)\r\n             ^^^^^","timestamp":"2024-01-07 13:44:55"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"4ce4cac7-c169-4285-be9c-e2c0a0aa352a","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:08:37"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"e5c5dfe3-995f-4d50-961a-62ff785166be","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:09:17"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"44b4f0e7-b05b-493f-9a3c-c5e34218ee29","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:09:24"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"ebb5fdb3-2fd2-43a5-a23b-0ea65f11ab24","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:09:25"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"ba394978-c18e-4cf6-b1c2-b287388330fc","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:11:27"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"d7f4acf7-57d3-4b54-bd9f-82df5bcfc1bb","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:11:58"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"6099b1c4-d12c-4e10-9022-974bfe8d0d77","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:12:24"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"6910651e-ab59-464d-be0f-1618f0be9f38","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:13:23"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"2e9659c2-05f2-4591-a3fd-3d14a884cb10","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:15:05"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"ff34f2e1-1102-4a50-af83-b9003866b80f","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:15:32"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"6258a827-2c02-4cd1-aa36-1469e2d50196","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:16:37"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"faf4ef64-16f8-4d21-93b0-84ac05070c64","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:11"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"9559162f-ade4-4b07-9d82-9bc85cb565ad","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:19"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"2251b427-5ef2-44b7-9dd5-c275e19d2db3","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:19"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"993c83dc-ada9-4144-b860-44f4c90e98cf","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:19"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"cd457253-fe50-4068-b2dd-8fcf1c65586e","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:20"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"efaf7d86-4331-4dec-9c1a-6e0b26a5d981","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:20"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"66ea3933-08ad-4965-9c94-33f56138e6cb","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:20"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"9aa48cc6-9c70-4fdc-abf9-4454de54b856","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:19:20"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"2e336f0f-899f-46ec-a271-bde7f41ee453","scriptId":"comandos0","stackTrace":"Error: ModuleNotFoundError: No module named 'objgraph'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 7, in <module>\r\n      import objgraph","timestamp":"2024-02-02 21:20:37"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"41d8e91a-6552-4d76-9098-998d7c1878ad","scriptId":"comandos0","stackTrace":"Error: C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py:323: DeprecationWarning: There is no current event loop\r\n  loop = get_event_loop()\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 324, in <module>\r\n    loop.run_until_complete(main())\r\n  File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n    return future.result()\r\n           ^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 288, in main\r\n    print(data)\r\n          ^^^^\r\nUnboundLocalError: cannot access local variable 'data' where it is not associated with a value\r\n\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:311:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)","timestamp":"2024-02-02 21:22:21"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"7f385135-1b21-470a-901f-967b5d649d9d","scriptId":"comandos0","stackTrace":"Error: C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py:317: DeprecationWarning: There is no current event loop\r\n  loop = get_event_loop()\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 318, in <module>\r\n    loop.run_until_complete(main())\r\n  File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n    return future.result()\r\n           ^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 283, in main\r\n    print(data)\r\n          ^^^^\r\nUnboundLocalError: cannot access local variable 'data' where it is not associated with a value\r\n\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:311:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)","timestamp":"2024-02-02 21:30:34"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"8bad42b0-43b3-434d-a51f-22fcba663e5d","scriptId":"comandos0","stackTrace":"Error: UnboundLocalError: cannot access local variable 'data' where it is not associated with a value\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 316, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 283, in main\r\n      print(data)\r\n            ^^^^","timestamp":"2024-02-02 21:33:57"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"01d6699b-ce1b-4546-afbd-d258632ff110","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 316, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 306, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:43:46"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"3df73be9-c9b8-4b99-a85c-27f9174313d8","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 316, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 306, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:44:06"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"0f61998c-ede8-49df-8d94-1c87a2c85823","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 317, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 307, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:45:07"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"f1b71ef2-fda8-4f37-a751-d67d488f3cb3","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 318, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 308, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:45:59"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"95fa9b3a-0c51-43b6-906a-3fe624bebd88","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 319, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 309, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:46:33"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"5d757065-4147-4478-a9cc-40f4ecb0d40f","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 319, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 309, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:47:02"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"69befdb9-2b3d-4f4b-bac5-5321b5a4ae07","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 319, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 309, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:47:11"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"d8518b6d-f6a0-4f02-a961-32ae7702a97d","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 317, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 307, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:47:47"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"6cdc1117-0421-489b-80ee-7cb6fae8cf60","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 317, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 307, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:47:50"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"6b8e1a27-2d22-4695-8db9-a16b0173952e","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 317, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 307, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:48:31"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"1b0e60c5-6243-4d34-8102-75fcef60b4a0","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 317, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 307, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:48:48"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"f92f046b-d8f0-42a3-a1e8-c233ab4eff81","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 318, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 308, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:49:15"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"afbc5200-ecc3-4347-a527-723cc2ed7ad9","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 319, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 309, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:49:32"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"9fdf9a86-ded0-4dd5-8d54-5d9f15bfa0a8","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 320, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 309, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:49:49"}
{"errorName":"Error","exitCode":1,"exitSignal":null,"level":"error","message":"Erro na execução do script comandos.py","requestId":"bff0b67d-6d3e-4225-a62d-23a241036b34","scriptId":"comandos0","stackTrace":"Error: KeyError: 'length'\n    at PythonShell.parseError (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:303:21)\n    at terminateIfNeeded (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:193:32)\n    at ChildProcess.<anonymous> (C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\node_modules\\python-shell\\index.js:185:13)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)\r\n    ----- Python Traceback -----\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 321, in <module>\r\n      run(main())\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 194, in run\r\n      return runner.run(main)\r\n             ^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\runners.py\", line 118, in run\r\n      return self._loop.run_until_complete(task)\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Python312\\Lib\\asyncio\\base_events.py\", line 684, in run_until_complete\r\n      return future.result()\r\n             ^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 310, in main\r\n      valido, mensagem = valida_comando(comando, COMANDOS)\r\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n    File \"C:\\Users\\joaop\\OneDrive\\Documents\\GitHub\\code-runner\\codes\\comandos.py\", line 266, in valida_comando\r\n      if config['type'] == \"string\" and config.get('length') != 'any' and len(valor) > config['length']:\r\n                                                                                       ~~~~~~^^^^^^^^^^","timestamp":"2024-02-02 21:50:47"}
